import { Field, Int, ObjectType } from 'type-graphql';
import { BaseEntity, Column, Entity, JoinTable, ManyToMany, PrimaryGeneratedColumn } from 'typeorm';
import { UploadColumn } from '../UploadColumn/UploadColumn.entity';

@Entity({ name: 'upload_entities_columns' })
@ObjectType({
    description:
        'Table describing the columns of a given entity that will be provided in data uploaded to the admin app',
})
export class UploadEntityColumns extends BaseEntity {
    @Field(() => Int)
    @PrimaryGeneratedColumn()
    id: number;

    @Field(() => String)
    @Column()
    entityName: string;

    @Field(() => [UploadColumn], {
        description:
            'The columns that for a given Entity that will be provided in a CSV uploaded to admin app. Not all columns will be uploaded (e.g. id, updatedOn etc, these fields will be generated by the server or database during the upload process.).',
    })
    @ManyToMany(() => UploadColumn)
    @JoinTable({ name: 'upload_entities_columns_upload_columns' })
    columns: UploadColumn[];
}
